### ISSUE TITLE
Introduction to `ember-graphql-adapter` at Global Ember Meetup

### ISSUE THREAD

**Issue by taras** [alphasights/ember-graphql-adapter#15]
Hi there, would you someone familiar with the project would be open to giving an "Introduction to ember-graphql-adapter" lightning talk at an upcoming Global Ember Meetup in the beginning of next year? We'll edit the video and give you video that you can embed into the addon's README. You can see an example of other introduction videos here https://vimeo.com/album/3607049

The talk usually covers:
1. What's use case for the addon?
2. How to get stated using it?
3. What should the user be aware of?

**Comment by jjbohn** [comment]
Hey @taras, when would you need it by?

**Comment by taras** [comment]
I'm currently booking for January 16th, 30th and Feb 13th

**Comment by jjbohn** [comment]
@taras, sounds like fun. I'm currently on paternity leave for the next week, but I'll talk to the gang when and see if we could come up with something. We'll definitely do something, just want to lock down the date that makes sense for us.

**Comment by taras** [comment]
I'm now booking for Feb 27th :)

**Comment by jjbohn** [comment]
Hey @taras back now. Yeah, this looks fun. When do we have to have the video to you by for Feb 27th? Will try to get it in well before hand, but just want to put the timeline together.

**Comment by taras** [comment]
@jjbohn No, the video is recorded live. We'll be hosting an event where all of the speakers and the audience will be in online space. When your time comes, you turn on screensharing and start speaking.

**Comment by jjbohn** [comment]
@taras Oh ok, great makes sense.

**Comment by taras** [comment]
Great, so should I book you for Feb 27th?

**Comment by jjbohn** [comment]
Yeah let's do it. @Arkham is actually working on slides for the London Ember meetup this week so we should be able to reuse those and the general premise of the talk.

**Comment by taras** [comment]
great :)

**Comment by taras** [comment]
Who will be giving the presentation?

**Comment by jjbohn** [comment]
Either myself or @Arkham. Going to chat with him this week and figure it out. Since he already has a presentation under way, it might make more sense for him to give it.

**Comment by taras** [comment]
Ok, please let me know so I'll know who to include in tweets about it

**Comment by Arkham** [comment]
This has been done, thanks @taras for organizing!
