### ISSUE TITLE
Create a demo app

### ISSUE THREAD

**Issue by jjbohn** [alphasights/ember-graphql-adapter#16]
We should do like a TodoMVC demo with a Rails GraphQL backend. Something that we could make a [deploy to heroku](https://devcenter.heroku.com/articles/heroku-button) button for and put all the code out there for people to see how to rig everything up. The `README` is a good starting place, but it'd be nice to go further with it.

**Comment by Arkham** [comment]
Definitely, I was just thinking about this yesterday :)

**Comment by willrax** [comment]
I can take this one.

**Comment by willrax** [comment]
rails side here: https://github.com/alphasights/todo-graphql
