### ISSUE TITLE
GET supports only query operation

### ISSUE THREAD

**Issue by mdbiscan** [alphasights/ember-graphql-adapter#184]
I'm trying to use your adapter, but I'm getting a this error with a mutation query:
```javascript 
account.js:17 createBankAccount Error: Error: Ember AJAX Request GET http://localhost:3000/graphql returned a 405
Payload (Empty Content-Type)
"GET supports only query operation"
```
This is the request:
```javascript
context:Class {store: Class, __ember1524240476438: null}
data: {query: "mutation bankAccountCreate { bankAccount: bankAcco…r thirdParty thirdPartyPaymentAccount visible } }"}
dataType: "json"
type: "GET"
```
It's strange to me that a mutation is a `GET`, rather than a `POST`, but I assume running a query with a mutation what Apollo needs to run the correct resolvers? Regardless, my request is denied.

I've set this up using a `createRecord` method and then running `save`:

```javascript
async createBankAccount(options) {
  const bankAccount = this.store.createRecord('bankAccount', options);
  try {
    await bankAccount.save();
  } catch (e) {
    console.warn(`createBankAccount Error: ${e}`)
  }
},
```

**Comment by BrandonSchreck** [comment]
It looks like you're calling the createRecord method incorrectly. Is options your bankAccount model?

`  /**
    Called by the store when a newly created record is
    saved via the `save` method on a model record instance.
    @method createRecord
    @param {DS.Store} store
    @param {DS.Model} type
    @param {DS.Snapshot} snapshot
    @return {Promise} promise
  */
  createRecord: function(store, type, snapshot) {
    return this.saveRecord(store, type, snapshot, { action: 'Create' });
}`

**Comment by delkopiso** [comment]
@mdbiscan The adapter uses GET by default for all it's requests, but that's also configurable:

https://github.com/alphasights/ember-graphql-adapter/blob/651c6b8079702a1a78b5ff962dec8b0fb9a07402/addon/adapter.js#L13

You can just extend the default adapter and set `httpMethod` to `'POST'`
