### ISSUE TITLE
Readme issue

### ISSUE THREAD

**Issue by martinstannard** [alphasights/ember-graphql-adapter#20]
After installing as described in the Readme I found I had to change the names of the adapter and serializer from `GraphQLAdapter` to `Adapter` and from `GraphQLSerilizer` to `Serializer`. 

Those original names aren't defined on the ember-graphql-adapter.

**Comment by Arkham** [comment]
Thanks, it has been fixed now! (I've left the `GraphQLAdapter` because it shouldn't matter)
