### ISSUE TITLE
Release new version with latest commit

### ISSUE THREAD

**Issue by jamesflorentino** [alphasights/ember-graphql-adapter#33]
Hi, in 4f1fe1614ee849b2a8112210b4696c86cf955676, the `async` behavior works as expected. Is there any plan to release a new version soon with these? Thanks for writing this adapter btw :beer:

**Comment by delkopiso** [comment]
[v0.2.0](https://github.com/alphasights/ember-graphql-adapter/releases/tag/v0.2.1) was just released.
