### ISSUE TITLE
Are headers supported?

### ISSUE THREAD

**Issue by cheerfulstoic** [alphasights/ember-graphql-adapter#52]
I'm trying to access [GitHub's GraphQL API](https://developer.github.com/early-access/graphql/guides/accessing-graphql/) and as far as I can tell from the code I can't set the `Authorization` header.  Is that correct?

**Comment by delkopiso** [comment]
You can set a `headers` property in the adapter which will be added to the request. 

For example,
```javascript
import Ember from 'ember';
import Adapter from 'ember-graphql-adapter';

const { computed, get, inject: { service }} = Ember;

export default Adapter.extend({
  currentUser: service(),
  endpoint: 'https://api.github.com/graphql',
  httpMethod: 'POST',

  headers: computed('currentUser.oauthToken', function() {
    let headers = {};
    const authToken = get(this, 'currentUser.oauthToken');

    if (authToken) {
      headers['Authorization'] = authToken;
    }

    return headers;
  })
});
```

or more simply,
```javascript
import Adapter from 'ember-graphql-adapter';

export default Adapter.extend({
  endpoint: 'https://api.github.com/graphql',
  httpMethod: 'POST',
  headers: { 'Authorization': oauthToken }
});
```

**Comment by cheerfulstoic** [comment]
Awesome!  That works except that it urlencodes the request body to the server (also I need to set `Content-Type': "application/json; charset=utf-8"` in the headers to get it not not send as form data)

If I change line 260 of the `request` function to `JSON.stringify` the request it works.  Like this:

```javascript
let ajaxOpts = this.ajaxOptions(url, JSON.stringify({ query: compiledQuery }));
```

Also, AFAIK I need to replace the `compile` function to specify my own query.  Any better ideas are definitely appreciated ;)

**Comment by delkopiso** [comment]
It's already sending it as JSON: https://github.com/alphasights/ember-graphql-adapter/blob/6deca9adc52e47721579674270e5894c19990d79/addon/adapter.js#L340

**Comment by cheerfulstoic** [comment]
It was sending JSON, but it the data was urlencoded for some reason, not sure why.  It might have something to do with jQuery.

My need was really simple so I just made my own adaptor to get my data, so I'll close for now.  Thanks for the help!
