### ISSUE TITLE
Multiple hasMany relationships generate wrong (nested) query

### ISSUE THREAD

**Issue by steffansluis** [alphasights/ember-graphql-adapter#75]
Given the model:
```javascript
export default Model.extend({
  name: attr('string'),
  parents: DS.hasMany('node'),
  children: DS.hasMany('node')
});
```

The adapter generates the following query:
```graphql
query node {
  node(id: "my_node_id") {
    id
    name
    parents {
      id
      name
      children {
        id
        name
      }
    }
  }
}
```

This seems to me to be faulty behavior, as the children should not be nested within the parents but rather be on the same level.

**Comment by delkopiso** [comment]
@steffansluis just so I understand there is only one model in this example, `app/models/node.js` right?

**Comment by delkopiso** [comment]
I was able to reproduce this bug. I'll try to fix it as soon as I can.

**Comment by delkopiso** [comment]
@steffansluis can you give that branch a spin 👆? It should fix the issue you're having.

**Comment by steffansluis** [comment]
@delkopiso It seems the PR indeed fixes my issue by changing the query to the solution as mentioned in the PR description.
